# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StudyNotes' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StudyNotes

  target 'StudyNotesTests' do
    inherit! :search_paths
    # Pods for testing
  end

 pod 'YYAsyncLayer'
 pod 'YYText'
 pod 'SDWebImage', '~> 3.8.2'
 pod 'ReactiveObjC'

end
